language:
    - cpp
sudo: required

matrix:
  include:
    # linux with gcc 8
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          install:
            - gcc-8
      dist: trusty
      env:
        - MATRIX_EVAL="CC=gcc-8 CXX=g++-8"
      compiler: gcc
    # linux with gcc 7
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          install:
            - gcc-7
      dist: trusty
      env:
        - MATRIX_EVAL="CC=gcc-7 CXX=g++-7"
      compiler: gcc
    # linux with gcc 6
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          install:
            - gcc-6
      dist: trusty
      env:
        - MATRIX_EVAL="CC=gcc-6 CXX=g++-6"
      compiler: gcc
    # linux with gcc (default)
    - os: linux
      dist: trusty
      compiler: gcc
    # linux with clang (default)
    - os: linux
      dist: trusty
      compiler: clang
    # linux with clang 3.8
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          install:
            - clang-3.8
      dist: trusty
      env:
        - MATRIX_EVAL="CC=clang-3.8 CXX=clang++-3.8"
      compiler: clang
    # osx with xcode8.3/gcc
    - os: osx
      osx_image: xcode8.3
      compiler: gcc
    # osx with xcode8.3/clang
    - os: osx
      osx_image: xcode8.3
      compiler: clang
    # osx with xcode9.2/gcc
    - os: osx
      osx_image: xcode9.2
      compiler: gcc
    # osx with xcode9.2/clang
    - os: osx
      osx_image: xcode9.2
      compiler: clang
    # osx with xcode/gcc (default)
    - os: osx
      compiler: gcc
    # osx with xcode/clang (default)
    - os: osx
      compiler: clang

before_install:
  - eval "${MATRIX_EVAL}"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo rm /usr/local/include/c++; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi

install:
  - ./.ci/install-deps.sh

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig; fi

script:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then ./waf configure --prefix=/usr --alsa --classic --dbus; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ./waf configure --opus=no --readline=no; fi
    - ./waf -v build
    - sudo ./waf -v install

branches:
  only:
    - /.*/

notifications:
  email: false
# vim:set ts=2 sw=2 et:
